/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sakamotodesu.shanghai.solver;

public class App {
    public static void main(String[] args) throws InvalidLayoutException {
        ShanghaiSolver solver = new ShanghaiSolver();
        //solver.solve(StageData.getNormal());
        //solver.solveByBreadthStart(StageData.getDendo());
        //solver.solverByGraph(StageData.getDendo());
        solver.validate(StageData.getDendo_ryota());
        solver.solveByPoint(StageData.getDendo_ryota(), 1);
    }

    public String getGreeting() {
        return "Hello world.";
    }
}
